from napari_plugin_engine import napari_hook_implementation
from PyQt5.QtWidgets import QWidget, QFileDialog
from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSlot

"""
each of these GUI files is generated by qtdesigner.
To generate a new .py file from the designer's .ui file, type this in terminal

pyuic5 -x <.ui input file> -o <.py output file>

"""

from recOrder.viewer.qtdesigner.recOrder_offline_06232021 import Ui_Form
from recOrder.viewer.plugin_offline import OfflineRecon


class RecOrderOffline(QWidget, Ui_Form):
    def __init__(self, napari_viewer):
        super().__init__()
        self.viewer = napari_viewer

        self.setupUi(self)

        self.config_path = None

        # connect to buttons
        self.qbutton_browse_config_file.clicked[bool].connect(self.set_config_load_path)

    @pyqtSlot(bool)
    def set_config_load_path(self):
        """
        Opens a FOLDER browser dialog
        :return:
        """
        print("CONNECTED SIGNAL")
        self.le_path_to_config.setFocus()
        result = self._open_file_dialog(self.config_path)

        # check that file is .yml type
        if '.yml' not in result:
            if self._warning_dialog_choice("configuration files must be of type .yml, continue?"):
                self.config_path = result
                print("Config folder path changed to = " + str(self.config_path))
            else:
                return
        else:
            self.config_path = result

    # returns a list of file names
    def _open_file_dialog(self, default_path):
        return self._open_dialog("select a yml file",
                                 default_path,
                                 kind='File')[0]

    def _open_dialog(self, title, ref, kind='Folder'):
        options = QFileDialog.Options()

        options |= QFileDialog.DontUseNativeDialog
        if kind == 'Folder':
            path = QFileDialog.getExistingDirectory(None,
                                                    title,
                                                    ref,
                                                    options=options)
        elif kind == 'File':
            path = QFileDialog.getOpenFileName(None,
                                               title,
                                               ref,
                                               options=options)
        else:
            raise TypeError("keyword 'kind' required for dialog")
        return path

    def _warning_dialog_choice(self, message: str):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        buttonReply = msg.warning(None,
                                  "recOrder Warning Popup", message,
                                  QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
        return buttonReply == QtWidgets.QMessageBox.Ok


class RecOrderOffline_Alternate(QWidget):
    def __init__(self, napari_viewer):
        super().__init__()
        self.viewer = napari_viewer
        self.ui = OfflineRecon(self)


@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    # you can return either a single widget, or a sequence of widgets
    # each widget is accessible as a new plugin that stacks in the side panel
    # return [RecOrderCombined, RecOrderOffline, RecOrderAcquisition, RecOrderCalibration]
    return [RecOrderOffline, RecOrderOffline_Alternate]

